### ISSUE TITLE
Error on PyCharm 2016.3: plugin depends on unknown plugin org.intellij.groovy 

### ISSUE THREAD

**Issue by renzo1974** [CeH9/PackageTemplates#1]
I tried to install your cool plugin in PyCharm but it is not working because of missing plugin. In PyCharm groofy is installed with the LivePlugin (see https://github.com/dkandalov/live-plugin).
Maybe you could fix this?

**Comment by InsaneDoggo** [comment]
Seems like [https://plugins.jetbrains.com/idea/plugin/1524-jetgroovy](url) Compatible with  IntelliJ IDEA only. I will try to rewrite some functionality to avoid dependency on this plugin. Actually i want to support all IDEA-based IDE's including PyCharm.

**Comment by InsaneDoggo** [comment]
I have done some changes. Plugin works in PyCharm now. Groovy script replaced with JavaScript, but all labels in UI still old(named as "Groovy"). Some UI windows also differs from released version, github documentation is old too.

I'll fix mentioned above problems with next release. At this moment u can use next guide(picture)
![quick_guide](https://cloud.githubusercontent.com/assets/7687412/22445292/6f3e0f60-e74f-11e6-9277-6300d6c749c8.png)

Link to download:
[PackageTemplates.zip](https://github.com/CeH9/PackageTemplates/files/740620/PackageTemplates.zip)

P.S. tested in PyCharm CE 2016.3.2

**Comment by renzo1974** [comment]
Wow! What a perfect support!!!
Thanks a lot for your quick and professional response. It works perfectly also on PyCharm Enterprise.
