### ISSUE TITLE
Add support for 'Project'-level templates

### ISSUE THREAD

**Issue by kool79** [CeH9/PackageTemplates#4]
Currently only global templates are supported. I.e. 'Select File Template' dialog contains templates only from global list.
Please, add project-level templates.
Note: to create project level template in IntelliJ IDEA: 
 1.  Main menu > File> Settings... > Editor > File and Code Templates 
 2. Select 'Project' in 'Schema' combo-box (at top-right)
 3. Add template as usual (with "+" button)

**Comment by InsaneDoggo** [comment]
Light debuging + post on [forum](https://intellij-support.jetbrains.com/hc/en-us/community/posts/115000102990-FileTemplateManager-didn-t-found-Project-level-FileTemplates) have no results, atm i have tasks with higher priority such as release v0.2. i'll try debug more deeper later.

**Comment by InsaneDoggo** [comment]
Hello, check out new v0.4.0 which support Project-level templates.
[changelog](http://ceh9.github.io/PackageTemplates/other/en/changelog/)
