### ISSUE TITLE
Suggestion: the lack of doc

### ISSUE THREAD

**Issue by ayqy** [CeH9/PackageTemplates#6]
Nice wrok, but it is not quite friendly to user, due to the lack of wiki.
Is there a help doc or wiki ?

**Comment by InsaneDoggo** [comment]
Hi, did you visit [Github Pages](http://ceh9.github.io/PackageTemplates/) ?

**Comment by ayqy** [comment]
I have visited the page and the two videos, but how to configure the plugin settings is confusing.

There are neither docs nor wiki about this, eg. right click on the folder icon to add files seems the Easter egg, because of no hover tips 👈

**Comment by InsaneDoggo** [comment]
"right click on the folder icon" described [here](http://ceh9.github.io/PackageTemplates/tutorials/en/basics/ ). What plugin settings you want to configure?

**Comment by ayqy** [comment]
<http://ceh9.github.io/PackageTemplates/en> is what I want. The language option button goes to  tutorials, which is really hard to get. Could we add a [Doc/tutorial](http://ceh9.github.io/PackageTemplates/en) link to the project README or the [home page](http://ceh9.github.io/PackageTemplates/)?

I am frustrated I ignored the language option button, and spent a few minutes on gussing:joy: the usage.

Thanks a lot, nice work!

**Comment by InsaneDoggo** [comment]
**Added explanation** 

![docs](https://cloud.githubusercontent.com/assets/7687412/26024333/028964ee-37d8-11e7-907e-8a33dcb60c6a.PNG)

**Also added wiki home page.**

![image](https://cloud.githubusercontent.com/assets/7687412/26024366/8b84b0d2-37d8-11e7-9189-8d75ccc0806d.png)
