### ISSUE TITLE
Importing and Exporting Troubles

### ISSUE THREAD

**Issue by gbroques** [CeH9/PackageTemplates#7]
First, thank you for all your hard work. This is an amazing plugin! I showed it to my team today and they were amazed.

**Version:** 0.4.2-beta

I'm having trouble with the importing and exporting feature. Not sure if the 0.4.2-beta supports it or not.

### Trouble with Exporting
The export feature doesn't copy my file template with a `ui.xml` extension. It works with `.java` files. Haven't tried templates with other extensions yet.

### Trouble with Importing
Importing doesn't seem to do anything. 
1. I click the little green arrow for importing.
2. Navigate to the `.json` file generated by the export.
3. Double-click the `.json` file.
4. Nothing seems to happen

Any help or clarification is greatly appreciated. Thanks again for the plugin!

**Comment by InsaneDoggo** [comment]
Hi, thx for report. Is **FileTemplate** custom(Created via IDE Settings)? Check exported **FileTemplates** in **yourPath/templateName/fileTemplates/yourTemplate.xml**  it should contains all **FileTemplates** (Excluding non custom). If template built-in you can duplicate it as custom with another name.

**Comment by gbroques** [comment]
The template is custom. Let me show you some screenshots to help clarify. Below you can see it's a custom file template with extension `ui.xml`:

![image](https://user-images.githubusercontent.com/12969835/28420466-d908e2ea-6d27-11e7-8bf3-af505c3ac63b.png)

Here's how Intellij names the file template on the file system:

![image](https://user-images.githubusercontent.com/12969835/28420528-0df0f1be-6d28-11e7-8b2b-e869438d0d8d.png)

You can see there's a special character, subscript "i", wrapping "ext" to denote the extension is `ui.xml`. Would that mess up the export?

P.S. I should also note my operating system is **Windows**. Maybe that is messing things up because Mac and Linux handle file extensions differently.

**Comment by InsaneDoggo** [comment]
You are right. IDE src contains funny [hardcode](https://github.com/JetBrains/intellij-community/blob/fb1792bc5d19aa616429a26ac447b7f3cee8f355/platform/lang-impl/src/com/intellij/ide/fileTemplates/impl/FTManager.java#L368-L384). I will try fix this ASAP.

**Comment by InsaneDoggo** [comment]
Fixed, try this version: #2

**Comment by gbroques** [comment]
It works. Thank you for the blazing fast fix! Importing also works now.

I'm closing this issue.
