### ISSUE TITLE
Favourite Issue

### ISSUE THREAD

**Issue by ellii** [CeH9/PackageTemplates#8]
Hello, i'm having a problem with favourite list. I have file structure like this:
packageTemplates -
     - MVVM.json
     - MVVMSubDir.json

and i can't put them both into favourite list. Just one at the time.

Files are almost the same just diferent with "name" and "skipRootDirectory"
Version 0.4.2

**Comment by InsaneDoggo** [comment]
Hello, you can **copy paste** template.json(actual file in IDE's **config/packageTemplates** directory, not imported file) and rename it. When you open newly created file via **select file\input path** property **name** will automatically changes according to FileName.  So you achieve two same template with different names, now you can edit them as you wish.

Don't forget mark checkBox before apply **Favorite** to selected via path template.

![pt_issue_duplicate_templates](https://user-images.githubusercontent.com/7687412/28412027-886b317a-6d4b-11e7-9095-310f2eb199c3.png)

**Comment by ellii** [comment]
Thanks for quick answer. I forgot the checkbox From path check box :/ 

Now its working perfectly

and is there any way to get package name?
I want to create something like:

main
->java
--> com.example.classFolder
---> oneClass.java
---> secondClass.java
->resources
--> com.example.classFolder
---> oneClass.fxml

so if i click on the java > classFolder and create new files with PackageTemplates it will create without problems oneClass.java and secondClasss.java but how can I create resources directory with the same package name and insert oneClass.fxml

**Comment by InsaneDoggo** [comment]
- **Create in custom lacation:** 
Use  [CustomPath](http://ceh9.github.io/PackageTemplates/tutorials/en/custom_path/) 
for example: 
![image](https://user-images.githubusercontent.com/7687412/28419578-1435d59a-6d68-11e7-8bee-4b07b99c9608.png)



- **Get PackageName**
Predefined Global Variable: **CTX_FULL_PATH** or **CTX_DIR_PATH**  [details](http://ceh9.github.io/PackageTemplates/tutorials/en/global_variables/)
You can edit this path via [Script](http://ceh9.github.io/PackageTemplates/tutorials/en/script/) for example:
![pt_package_name](https://user-images.githubusercontent.com/7687412/28419309-37e0f67e-6d67-11e7-99fd-56044076de87.png)
