### ISSUE TITLE
Add Tooltips to Buttons

### ISSUE THREAD

**Issue by gbroques** [CeH9/PackageTemplates#9]
In order to know what the buttons do, you have to refer to the [Basics](http://ceh9.github.io/PackageTemplates/tutorials/en/basics/) page.

![image](https://user-images.githubusercontent.com/12969835/28475739-1617f16c-6e13-11e7-9b7a-eb55c84b808c.png)

Most of the icons are intuitive, but **I always mix up the purple and green arrow icons** for exporting and importing.

**Feature Request:** I think adding tooltips to the buttons would make the plugin easier to use.

**Comment by InsaneDoggo** [comment]
Thx for advice, i'll add tooltips in next release. P.S. **Import** arrow point to rectangle, **Export** arrow goes from it.

**Comment by gbroques** [comment]
I'm actually creating a pull request for this now.

**Comment by InsaneDoggo** [comment]
Ok, would be great.
